### ISSUE TITLE
Enable support for running hypertrace with Postgres as an alternative document store

### ISSUE THREAD

**Issue by kotharironak** [hypertrace/hypertrace#124]
## Use Case
Enable support for running hypertrace with Postgres as alternative document-store along with mongo

## Proposal

- enable to run hypertrace with Postgres or mongo as document store in docker-compose
- enable conditional deployment support in the helm for Postgres

Ref work: 
- https://github.com/hypertrace/document-store/pull/9 (provides an implementation of the document-store interface for Postgres)

**Comment by adriancole** [comment]
probably switching default to postgres makes most sense because it doesn't have the odd licensing problems as MongoDB has. For example, alpine linux cannot distribute an OS packag for MongoDB anymore since its last weird license. postgresql is a little behind, but still updated

https://pkgs.alpinelinux.org/packages?name=postgresql

iotw, maybe just assume most don't want mongo, and switch the default? So far we've heard a lot of feedback about how to not use mongo.

**Comment by buchi-busireddy** [comment]
@kotharironak Is this fully ready? Even in helm based setup?

**Comment by kotharironak** [comment]
> @kotharironak Is this fully ready? Even in helm based setup?

docker-compose setup has been added, helm setup is pending.
