### ISSUE TITLE
Automate release notes generation for Hypertrace repos

### ISSUE THREAD

**Issue by JBAhire** [hypertrace/hypertrace#156]
## Use Case
As a part of larger effort of having proper release notes across all repositories we should add automated job in GitHub Actions workflow to automate that process. 

## Proposal
- Add Gren bot (https://github.com/github-tools/github-release-notes#feed-gren-) to get create automatic release notes.
- Added this as a part of publish workflow in GitHub actions so it will automatically run every time we publish new release. 
- Added `.grenrc.js` which formats the output of GREN bot according to our requirements. 

This utility uses labels for grouping PRs into categories so please use appropriate labels in upcoming PRs. 

In order to have splendidly generated release notes, we recommend to follow these conventions:

-   Start the subject line with a verb (e.g. Change header styles)
-   Use the imperative mood in the subject line (e.g. Fix, not Fixed or Fixes header styles)
-   Limit the subject line to about 50 characters
-   Do not end the subject line with a period
-   Separate subject from body with a blank line
-   Wrap the body at 72 characters
-   Use the body to explain what and why not how

Tracking change: 
- [x] https://github.com/hypertrace/kafka 
- [x] https://github.com/hypertrace/pinot 
- [x] https://github.com/hypertrace/zookeeper 
- [x] https://github.com/hypertrace/mongodb 
- [x] https://github.com/hypertrace/schema-registry 
- [x] https://github.com/hypertrace/query-service
- [x] https://github.com/hypertrace/gateway-service
- [x] https://github.com/hypertrace/attribute-service
- [x] https://github.com/hypertrace/hypertrace-service 
- [x] https://github.com/hypertrace/config-service 
- [x] https://github.com/hypertrace/entity-service
- [x] https://github.com/hypertrace/hypertrace-graphql
- [x] https://github.com/hypertrace/hypertrace-ingester 
- [x] https://github.com/hypertrace/hypertrace-ui

## examples
- https://github.com/hypertrace/pinot/pull/61

**Comment by aaron-steinfeld** [comment]
@JBAhire So unfortunately I didn't see this until now (and already helped merge a bunch :) ) but after the fact, started thinking a bit about it. We don't necessarily need to address these now (or possibly ever), but I want to throw them out for discussion:

### Release workflow
Currently, the flow looks like:
  - User creates a release manually in the GH UI, picking a version, and publishing it
  - The published release kicks off actions - publishing artifacts and creating a new release with notes that overwrites the existing one

Given this process, would it make more sense to instead:
  - Add a "Cut Release" workflow that takes in no parameters and is only initiated via dispatch
  - This would then first publish artifacts
  - If successfully published, it then creates a github release with release notes

The benefits of this switch would be:
 - If there are issues publishing, no release is cut (no skipped release numbers)
 - Releases are ready to consume from the moment they're published (currently, a new release notification comes before the artifacts are published, so automation can't rely on it)
 - No user selection of version numbers (forcing us to follow semantic versioning to match our release notes)
 - If we wanted to maintain a changelog in source code (a good idea), updating and committing it before generating artifacts and cutting the release could also be part of this workflow.

Not a top priority, but something to consider.

### Release notes data
I have a few questions about what goes into the release notes. It's unclear to me why https://github.com/hypertrace/hypertrace-ui/releases/tag/0.69.2 was generated as a feature for example. Can we filter down so only features and bug fixes show up in the notes? It looks like it's tied to the pull request rather than the commit message.

### Library
Why did we choose gren? The library I commonly see (and that we use elsewhere in HT) is `semantic-release`:

just to compare the two in terms of traffic:
https://www.npmjs.com/package/github-release-notes - 3K weekly downloads, last updated 9 months ago
https://www.npmjs.com/package/semantic-release - 370K weekly downloads, last updated today (and generally updated regularly)

**Comment by JBAhire** [comment]
Okay!

### Release workflow:
I completely agree on having workflow that's based on `workflow_dispatch` that will cut the release and publish artifacts and that will simplify things for everyone. I thought of this earlier but I had few concerns about it so never ended up doing it. 

One major concern is re-running the jobs. Cutting a release will never fail as it will just follow semantic versioning and cut the release but the concern starts when publish fails. When publish fails, we can just hope for someone to not re-run the job or else we will end up creating multiple jobs so that sense of ownership is still there. And again, cutting a release from UI basically reduces the uncertainty behind this. 

But yeah, I can see it making things easier. I am ready to give this a thorough thought and change this. But I will prefer to do it after macro repo transition due to obvious reasons. 😅 

### Release notes data:
So, we are not using commit data here because we use squash and merge which anyways only adds one commit i.e. pull request title. Usually commits won't have any labels so it's hard to categorize them. You might parse and categorise on the basis of prefix (eg. `ci:`) but when we have nice label functionality available, using that seemed like a better option. 

We can change `.grenrc` file to only show categories we want to show. Right now there are 5 of those which are generally followed by many major OSS projects but in future if we want to reduce down categories, it just removing few lines in `.grenrc`. 

About changelog, I attempted it here (https://github.com/hypertrace/pinot/pull/61/files/141f9edf5045bb41a7b98914edd2760a7af4dd80#diff-68d24fa81558aae3d8c59e2aa57a4fa719ea3b04d7fa14beff45f16f00858f50) and gren supports changelog generation so we can add it to our action and use it. It's simple to implement. 

### Library
I looked at semantic-release library and it is more of a semantic release automation on the basis on commit messages. We don't want to automate releases, we just wanted to have release notes on releases we do. 

gren solves and handles the release note generation task really well and it's highly configurable with various options. It's a tool which does single job but does it very well. 

Even if go with semanctic-release, I don't see a lot of value in many places and we still need to have separate job or step for release note generation. makes sense?

**Comment by aaron-steinfeld** [comment]
> One major concern is re-running the jobs. Cutting a release will never fail as it will just follow semantic versioning and cut the release but the concern starts when publish fails. When publish fails, we can just hope for someone to not re-run the job or else we will end up creating multiple tags so that sense of ownership is still there. And again, cutting a release from UI basically reduces the uncertainty behind this.

I'm not sure I agree here. If we set it up correctly, a tag is only applied once everything is successful. Rerunning it on something successfully tagged could easily be set up to short circuit and not run. On the other hand, the currently manual step of deciding on the tag and making sure it follows semver is made automatic.

> So, we are not using commit data here because we use squash and merge which anyways only adds one commit i.e. pull request title. Usually commits won't have any labels so it's hard to categorize them. You might parse and categorise on the basis of prefix (eg. ci:) but when we have nice label functionality available, using that seemed like a better option.

Squash and merge does add a single commit, but it still on the author to write the message for that commit - it's only lack of awareness (or dare I say laziness!) that causes us to use the default github suggests. I strongly prefer tying to commits rather than pull requests for a couple reasons (some of which, admittedly, may be preference). 

Commit messages ultimately should be your source of truth for changes to a repo. Git is the VCS tool, not github and we want the commit history to be useful independently of the tool we use to host (which may always change in the future). If the commit message _also_ has this information, then we're just driving duplicate work, and if it doesn't, even worse we're leaving important details out of the commit log. The more we can integrate (and validate/automate) as part of the developers pre-push workflow, the better in my mind. This is certainly driven at least in part by my own work style, but the more I have to do in the github UI, the more friction for me. Commit messages I have to write anyway, and are already validated before I ever push them (although I'm sure we can do similar validation on the PR labels).

> I looked at semantic-release library and it is more of a semantic release automation on the basis on commit messages. We don't want to automate releases, we just wanted to have release notes on releases we do.
> 
> gren solves and handles the release note generation task really well and it's highly configurable with various options. It's a tool which does single job but does it very well.
> 
> Even if go with semantic-release, I don't see a lot of value in many places and we still need to have separate job or step for release note generation. makes sense?

They're pretty similar in terms of what we're accomplishing, but if we don't need it, it of course doesn't really matter - more just curiosity. Semantic release, like gren, is triggered by invoking it in a workflow. Like gren, it then generates release notes, creates a github release etc. It has many [plugins](https://github.com/semantic-release/semantic-release/blob/master/docs/extending/plugins-list.md) doing things like updating licenses, supporting multiple release channels, updating a changelog, notifying slack etc. So I know it does more than gren, but certainly covers our use cases and some others we've yet to tackle. Anyway, not worth making a change just for the sake of it, but if we start needing to add some of these other pieces of functionality, it might be nice to keep things simple and use one tool.

**Comment by JBAhire** [comment]
Thanks @aaron-steinfeld ! Let's try to address your suggestions in next iterations. I agree on most of it.

**Comment by kotharironak** [comment]
@JBAhire Should we keep this open?

**Comment by JBAhire** [comment]
I will create separate issues for things we want to address from above discussion. Let’s use those independent issues and link this discussion there.
